### ISSUE TITLE
blynk won't compile with latest chaos calmer

### ISSUE THREAD

**Issue by Zephael86** [vshymanskyy/blynk-library-openwrt#1]
blynk package is missing references to librt during compile.
I solved it by editing the Makefile

chaos_calmer_folder/feeds/blynk/blynk/Makefile

before:
DEPENDS:=+libpthread $(CXX_DEPENDS)

after:
DEPENDS:=+librt +libpthread $(CXX_DEPENDS)

**Comment by vshymanskyy** [comment]
Fixed
