### ISSUE TITLE
Can't get Blynk running on Archer C7

### ISSUE THREAD

**Issue by bufferunderrun23** [vshymanskyy/blynk-library-openwrt#2]
Thank you so much for your work, I love Blynk and already bought some Energy =)

Now I try to get it running on a TP-Link Archer C7 router, but can't get it to work.
I'm getting the following error:
`root@OpenWrt:~# ls`
`blynk_0.3.11-1_ar71xx.ipk`
`root@OpenWrt:~# opkg install blynk_0.3.11-1_ar71xx.ipk `
`Installing blynk (0.3.11-1) to root...`
`Configuring blynk.`
`root@OpenWrt:~# blynk`
`-ash: blynk: not found`
`root@OpenWrt:~# cd /usr/bin/`
`root@OpenWrt:/usr/bin# ls -la blynk `
`-rwxr-xr-x    1 root     root         16469 Feb  5 12:06 blynk`
`root@OpenWrt:/usr/bin# blynk`
`-ash: blynk: not found`
`root@OpenWrt:/usr/bin# ./blynk `
`-ash: ./blynk: not found`
`root@OpenWrt:/usr/bin# `

This is the first time that I compiled an ipk for OpenWRT myself.
I did the following steps:
1) Installed OpenWRT build system (using this guilde: https://wiki.openwrt.org/doc/howto/buildroot.exigence)
2) Used the following commands:
`make tools/install
make toolchain/install`
3) Did what your readme.md describes, in make menuconfig I selected `<M>` at blynk
4) Transfered the generated .ipk from 'openwrt_buildroot/openwrt/bin/ar71xx/packages/blynk' to the router
5) Issued 'opkg install blynk_0.3.11-1_ar71xx.ipk'

What am I doing wrong?
Thanks for your help in advance.

BTW: It would be so awesome, if you could provide an already compiled .ipk for ar7xxx

**Comment by vshymanskyy** [comment]
I'm unsure, did you try building with * and flashing whole firmware?

**Comment by bufferunderrun23** [comment]
Thanks alot for your answer. I also tried building and flashing the whole firmware but it did not work. 
Maybe it's related to the Archer C7 and not Blynk.
To save time, I bought a raspberry pi and use blynk with node.js now =)
